### ISSUE TITLE
atc: circle command is not working properly

### ISSUE THREAD

**Issue by lukascalda** [msharov/bsd-games#10]
There are many bugs I do not understand. Circle command does not circle, it makes one circle then the plane leaves the screen. It is not possible to circle left or right. It does not make hard left or right, purely strange.
Neither you can choose game you want. So buggy I dont get it.

**Comment by msharov** [comment]
Unlike many other games in the package, I did not comprehensively rewrite atc, so it acts just like it did when first written decades ago. If circling did not work then, it still does not work. You are welcome to implement this feature properly and submit a PR; I'm wary of touching that code myself as it is twisty and full of magic.

As for "choosing game you want", you specify the scenario you want to play as an argument when you start atc. You can get a list of scenarios with `atc -l`.

**Comment by lukascalda** [comment]
Hi, I did not explain myself correctly. I know how this game works/should work. I have played it a lot years ago. This one does not act how it is supposed to. 
Maybe the code is ok and there is something strange with my terminal. Dunno.

**Comment by msharov** [comment]
Unfortunately, I have never been able to figure out how to play this game, and all the cleanup was carried out with the minimal testing of verifying that the menu works and the planes move around. This, naturally, is bad coding practice, because it can cause a variety of errors like these that I would have no way of noticing. I can fix crashes or obviously broken stuff, but subtle misbehavior in the plane routing algorithm is rather beyond my abilities here. All I have been able to check is that the circle command does set plane direction to a magic value, presumably meaning to circle. The value does not appear to be checked anywhere else in the code, so that code was either accidentally deleted or some clever overflow exploits were used to update direction from there. I'm unsure where to go from here.

Since you at least know how to play the game and can reproduce the problem, perhaps you could build a debug version (`make debug=1`) and troubleshoot it.

**Comment by msharov** [comment]
I have found a possible culprit, where I assumed that plane direction was supposed to be computed as one of the actual valid directions, whereas while circling the direction has a different meaning.

Please pull up to commit 511ca9eb1fe71d3ab1948c0e3b61336150ff389e and check if that fixes the problem.

**Comment by lukascalda** [comment]
Hi, thanks for your time! Will try to look into into it asap.

**Comment by lukascalda** [comment]
Hi, this did the trick. Circling now works as it should be. Still does not work circle left or right but I am not sure, if it worked before. I just circle :)
