### ISSUE TITLE
please add trek back

### ISSUE THREAD

**Issue by RussellSenior** [msharov/bsd-games#3]
It is the only game out of bsd-games I actually still play

**Comment by msharov** [comment]
I'm working on it. Due to copyright problems, all Star Trek references must be removed. The game will be renamed "Space Pirate Hunt", with no Klingons, Spock, or other TOS characters.

**Comment by RussellSenior** [comment]
Did anyone actually complain, or is that just pre-emptive on your part? I'm primarily interested because I played this game in the late 1970s, and those elements are important to the experience. If necessary, I'll just fork from the old version for my use.

**Comment by msharov** [comment]
No, nobody complained, and there is a legal argument to be made about this not being prosecuted for fifty years. Nevertheless, using Star Trek content makes trek a derived work, and thus illegal to distribute. Being able to get away with it some of the time is irrelevant, since any lawsuit in the US is a financial death sentence whether you are found guilty or not. You wouldn't want something bad to suddenly happen to those Regents of the University of California, would you?

As for the experience, I disagree. The Enterprise never participated in the Klingon war in TOS, so this is not canon anyway. The Klingons in the game do not act like Klingons either, running away and having to be chased down all the time. That's pirate behavior. Mentioning Star Trek characters also does not add anything of value, being infrequent and unimportant to gameplay. The game also feels more like police action than a war, with the Enterprise flying around alone. In my opinion, removing all the Trek stuff actually helps the game make more sense.

**Comment by msharov** [comment]
Commit 28ba9b0bcf221e2652abf9c12b5aa03f56fab9ce adds trek back as spirhunt, with all Star Trek stuff removed. The game is as playable as trek was, with no visual improvements for now.
