### ISSUE TITLE
Numerous scoring bugs in cribbage

### ISSUE THREAD

**Issue by jvolkening** [msharov/bsd-games#7]
Hello,

I found your repo after wondering if anyone had tried to improve the visuals of the old bsd cribbage game using modern Unicode characters, etc. Your interface is a nice improvement over the original one. However, I noticed numerous major errors in the scoring functions for the game. They must have been re-written since the original game did not have these issues. I started to write a PR for the first one, but then they just keep cropping up. So far:

1. The game gives all players "one for nobs" if heels is turned up. It checks to see if a player has the matching jack in their hand, but not if that jack is actually identical to the turn-up/starter.

![image](https://user-images.githubusercontent.com/11667655/95039313-04c7dc00-0696-11eb-8808-53ed9796c57f.png)

2. It scores a four-card flush even if the turn-up is included as one of those cards (i.e. not all four cards in the hand are the same suit). 

![image](https://user-images.githubusercontent.com/11667655/95039350-1c9f6000-0696-11eb-8bc0-84286fa2b11b.png)

3. It scores non-consecutive cards of matching ranks as pairs (below, the play was 6D, 5S, 6C, 5C, and both players were given points for pairs.

![image](https://user-images.githubusercontent.com/11667655/95039565-bd8e1b00-0696-11eb-92e2-9699ec693d00.png)

4. The pegging graphic is wrong (asterisks do not match actual score -- see above for example). 

Best,
Jeremy

**Comment by msharov** [comment]
Ok, I'll take a look at it sometime.

Yes, the scoring rules were rewritten, and since I have never actually played cribbage I used rules from a book on card games. The rules are weird, so obviously I had difficulty figuring out how they work. For 3, for instance, the rules make no mention of requiring pair cards to be consecutive. See the Wikipedia entry on Cribbage for example; it merely states "completing a pair" rather than making a pair with the last played card.

**Comment by jvolkening** [comment]
Sure, I can see that the rules might be unclear without any playing experience. During the play stage, pairs/3-of-a-kind/4-of-a-kind means cards played consecutively and in the same run of counting (if one card ends in a "go", and then a matching cards starts after the reset, it's not a pair).

A flush requires the four cards in the hand to be the same suit, for four points. If the turn-up card matches it's an extra point, but you can't have a four-card-only flush that includes the turn-up card. The crib is slightly different in that all five cards must match -- there can't be a four-card flush in the crib.

I just want to mention also that I thought the requirement in the original game to count your own score, rather than have the program do it all for you, was a good feature. This is good practice, and it allows to emulate certain (optional) rules wherein the opponent can get points if you make a mistake in your score calculation during the "show". Then the software can tell you if you made a mistake.

**Comment by msharov** [comment]
I thought that having to count your own score was the single worst thing about the old implementation. First, because it was unfair - the computer never makes any mistakes, so *you* never points from these rules. Second, because the very idea seems so tedious and boring that I really wondered why anyone would want to play this game in real life. Here you memorize dozens of rules that have no sense or logic, then have to meticulously pay attention to your mental arithmetic lest your opponent scores from your mistakes. Seriously, where's the fun here? I can kinda understand why people play poker or blackjack, even though I never do, but I don't understand the appeal of this game at all.

**Comment by jvolkening** [comment]
> Here you memorize dozens of rules that have no sense or logic, then have to meticulously pay attention to your mental arithmetic lest your opponent scores from your mistakes. Seriously, where's the fun here?

Ha - to each their own, I guess. I would say that the first part applies to a greater or lesser extent to most of the card games that I grew up playing -- euchre, sheephead, hearts, spades, cribbage. I'm not sure a "justify your existence" debate in support of cribbage is in scope here, though.

Re: scoring, it should definitely be optional, and perhaps off by default. The benefit is to force someone who is learning the game to actually learn how to score, which as you say is not straightforward at first and takes practice. I didn't learn cribbage from software, but I actually think it could be incredibly useful to be able to practice the scoring and then have the software tell you when you're wrong, so you can figure out your mistakes.

It's really a matter of opinion, though. Any time is best spent fixing the actual bugs. I may work on a PR if I ever have some free time.

**Comment by msharov** [comment]
Commit 6e8f009ed99811c6dbd58916397d5f9d2999dfa2 fixes peg display issues of point 4.
