### ISSUE TITLE
Computer can play card over 31 instead of Go

### ISSUE THREAD

**Issue by donflanGIT** [msharov/bsd-games#8]
I am not a developer.  I joined to report bugs with cribbage.  Someone made a Gentoo package for bsd-games-3.1, so that's where I got it.  I filed a bug with them, but I don't know if it will make it to you.

First, the computer will sometimes play a card that makes the count exceed 31.   Then it says it won that hand. That's a big rule violation.  I can't see a pattern to make it repeat this bug.  
Second, the computer will unnecessarily lead with a 5.  For example, it led 5 and I played a ten for 15.  Then the computer played a 4.  Leading with a 5 is pretty much giving away 2 points.
I read the previous issue and smiled when it said the computer doesn't make mistakes.

I tried downloading the latest bsd-games here, but it fails to build on my Slackware machine. I read the README, but the make fails with probably the second game.

The previous commenter mentioned manual scoring.  FWIW, I'm with him.

**Comment by msharov** [comment]
No, I don't get the bugs you file with gentoo; I wasn't even aware it was being packaged there.

I'll look into the over-31 problem.

Can you please explain more about why leading with a 5 is bad? You can't know whether your opponent has any 10s, and you will have to play the 5 eventually anyway, won't you?

The computer, of course, never makes mistakes. It only does what I tell it, perfectly. Since I am not an expert cribbage player (in fact, I have never played it in real life), I am quite fallible here and must perforce rely on people reporting problems to see if anything is going wrong.

The manual scoring is already implemented in 3.1 by adding a pause before the show, during which you are free to do manual scoring and then compare with the computer-generated results once your resume.

Finally, the build failure is an entirely separate matter. Please file a separate issue for it, with a full list of build failures. I can't just read your screen from here you know...

**Comment by thesamesam** [comment]
@msharov Thanks by the way. I packaged this in Gentoo recently after finally getting around to it from your email from a while back.

**Comment by donflanGIT** [comment]
I think I failed to respond properly to this:
>Can you please explain more about why leading with a 5 is bad? You can't know whether your opponent has any 10s, and you will have to play the 5 eventually anyway, won't you?

There are sixteen cards with  a value of ten.  The odds are high that your opponent has one in his/her hand.  A play for a 15 gets a premium score of 2.  A human would quickly learn to not lead with a 5 after gifting two points to the other player.  I would imagine that all existing, well-established cribbage programs have some logic preventing such a play.    
Never lead 5 unless forced.   It's rare to be dealt four 5s and _have_ to lead that way.

**Comment by msharov** [comment]
All right, I think I see the issue here. Commit 65912a69624db2c992eb5149657be3183dec61ac lets AI consider it.

**Comment by msharov** [comment]
Also, don't forget to file a bug for the build failures you had on Slackware.
This illustrates why it is not a good idea to report multiple problems in a single issue; we inevitably lose track and ignore some.
